name: Daily Bossa Scan

on:
  schedule:
    # 0 minut, 17 godzina (UTC) = 18:00 w Polsce
    # Uruchamiaj TYLKO o pełnej godzinie
    - cron: '0 17 * * 1-5'
  
  # Pozwala na ręczne uruchomienie przyciskiem
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas yfinance ta

      - name: Run Scanner Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python scanner_bot.py
